### ISSUE TITLE
Schematic or connection?

### ISSUE THREAD

**Issue by nmaggioni** [markqvist/TelemetryKit#1]
I've looked at the code, but couldn't locate any reference to the pins that must be used to transmit/receive with the library. Is a schematic available?

**Comment by markqvist** [comment]
This project is really old and has not been maintained for a long time. It's an offshoot of an early version of LibAPRS, and AX.25 modem and APRS library for Arduino. You might have better luck using that actually. If you want to use TelemetryKit, it's the same pinout as LibAPRS and MicroModem, more info here: https://unsigned.io/micromodem/
